version: '3'

services:
  jenkins1:
    image: jenkins/jenkins:lts
    container_name: jenkins1
    ports:
      - "8080:8080"
    volumes:
      - jenkins1_home:/var/jenkins_home

volumes:
  jenkins1_home:
